
CREATE TABLE CIUDAD (
  ID_CIUDAD       NUMBER       PRIMARY KEY,
  NOMBRE          VARCHAR2(250 CHAR) NOT NULL,
  CONSTRAINT UQ_CIUDAD_NOMBRE UNIQUE (NOMBRE)
);

CREATE TABLE USUARIO_SERVICIO (
  ID_USUARIO_SERVICIO NUMBER       PRIMARY KEY,
  NOMBRE              VARCHAR2(250 CHAR) NOT NULL,
  CORREO              VARCHAR2(250 CHAR) NOT NULL,
  TELEFONO            VARCHAR2(50 CHAR)  NOT NULL,
  CEDULA              VARCHAR2(50 CHAR)  NOT NULL,
  CONSTRAINT UQ_USRSERV_CORREO UNIQUE (CORREO),
  CONSTRAINT UQ_USRSERV_CEDULA UNIQUE (CEDULA)
);

CREATE TABLE USUARIO_CONDUCTOR (
  ID_USUARIO_CONDUCTOR NUMBER       PRIMARY KEY,
  NOMBRE               VARCHAR2(250 CHAR) NOT NULL,
  CORREO               VARCHAR2(250 CHAR) NOT NULL,
  TELEFONO             VARCHAR2(50 CHAR)  NOT NULL,
  CEDULA               VARCHAR2(50 CHAR)  NOT NULL,
  COMISION             NUMBER             NOT NULL,
  CONSTRAINT UQ_USRCOND_CORREO UNIQUE (CORREO),
  CONSTRAINT UQ_USRCOND_CEDULA UNIQUE (CEDULA),
  CONSTRAINT CK_USRCOND_COMISION CHECK (COMISION BETWEEN 0 AND 1)
);

CREATE TABLE VEHICULO (
  ID_VEHICULO          NUMBER       PRIMARY KEY,
  TIPO                 VARCHAR2(250 CHAR) NOT NULL,
  MARCA                VARCHAR2(250 CHAR) NOT NULL,
  MODELO               VARCHAR2(250 CHAR) NOT NULL,
  COLOR                VARCHAR2(250 CHAR) NOT NULL,
  PLACA                VARCHAR2(50 CHAR)  NOT NULL,
  CAPACIDAD            NUMBER             NOT NULL,
  ID_USUARIO_CONDUCTOR NUMBER             NOT NULL,
  ID_CIUDAD_EXPEDICION NUMBER             NOT NULL,
  CONSTRAINT UQ_VEHICULO_PLACA UNIQUE (PLACA),
  CONSTRAINT CK_VEHICULO_TIPO CHECK (UPPER(TIPO) IN ('CARRO','CAMIONETA','MOTOCICLETA')),
  CONSTRAINT FK_VEH_CONDUCTOR FOREIGN KEY (ID_USUARIO_CONDUCTOR)
    REFERENCES USUARIO_CONDUCTOR (ID_USUARIO_CONDUCTOR),
  CONSTRAINT FK_VEH_CIUDAD FOREIGN KEY (ID_CIUDAD_EXPEDICION)
    REFERENCES CIUDAD (ID_CIUDAD)
);

CREATE TABLE PUNTO_GEOGRAFICO (
  ID_PUNTO NUMBER PRIMARY KEY,
  NOMBRE   VARCHAR2(250 CHAR),
  LATITUD  FLOAT NOT NULL,
  LONGITUD FLOAT NOT NULL,
  DIRECCION VARCHAR2(250 CHAR) NOT NULL,
  ID_CIUDAD NUMBER NOT NULL,
  CONSTRAINT FK_PUNTO_CIUDAD FOREIGN KEY (ID_CIUDAD)
    REFERENCES CIUDAD(ID_CIUDAD)
);

CREATE TABLE SOLICITUD_SERVICIO (
  ID_SOLICITUD NUMBER PRIMARY KEY,
  TIPO   VARCHAR2(250 CHAR)  NOT NULL,
  NIVEL  VARCHAR2(50 CHAR),
  FECHA  DATE NOT NULL,
  ESTADO VARCHAR2(250 CHAR)  NOT NULL,
  ID_USUARIO_SERVICIO NUMBER NOT NULL,
  ID_PUNTO_PARTIDA    NUMBER NOT NULL,
  CONSTRAINT CK_SOL_TIPO CHECK (UPPER(TIPO) IN ('PASAJEROS','COMIDA','MERCANCÍAS','MERCANCIAS')),
  CONSTRAINT CK_SOL_NIVEL CHECK (NIVEL IS NULL OR UPPER(NIVEL) IN ('ESTANDAR','CONFORT','LARGE')),
  CONSTRAINT CK_SOL_ESTADO CHECK (UPPER(ESTADO) IN ('CREADA','ASIGNADA','CANCELADA')),
  CONSTRAINT FK_SOL_USR FOREIGN KEY (ID_USUARIO_SERVICIO)
    REFERENCES USUARIO_SERVICIO(ID_USUARIO_SERVICIO),
  CONSTRAINT FK_SOL_PUNTO FOREIGN KEY (ID_PUNTO_PARTIDA)
    REFERENCES PUNTO_GEOGRAFICO(ID_PUNTO)
);

CREATE TABLE VIAJE (
  ID_VIAJE NUMBER PRIMARY KEY,
  FECHA_ASIGNACION DATE NOT NULL,
  HORA_INICIO DATE NOT NULL,
  HORA_FIN    DATE NOT NULL,
  DISTANCIA_KM FLOAT NOT NULL,
  COSTO_TOTAL  FLOAT NOT NULL,
  ID_USUARIO_CONDUCTOR NUMBER NOT NULL,
  ID_VEHICULO          NUMBER NOT NULL,
  ID_PUNTO_PARTIDA     NUMBER NOT NULL,
  ID_SOLICITUD         NUMBER,
  CONSTRAINT CK_VIAJE_TIEMPO CHECK (HORA_INICIO <= HORA_FIN),
  CONSTRAINT FK_VIA_COND FOREIGN KEY (ID_USUARIO_CONDUCTOR)
    REFERENCES USUARIO_CONDUCTOR(ID_USUARIO_CONDUCTOR),
  CONSTRAINT FK_VIA_VEH FOREIGN KEY (ID_VEHICULO)
    REFERENCES VEHICULO(ID_VEHICULO),
  CONSTRAINT FK_VIA_PUNTO FOREIGN KEY (ID_PUNTO_PARTIDA)
    REFERENCES PUNTO_GEOGRAFICO(ID_PUNTO),
  CONSTRAINT FK_VIA_SOL FOREIGN KEY (ID_SOLICITUD)
    REFERENCES SOLICITUD_SERVICIO(ID_SOLICITUD)
);

CREATE TABLE DISPONIBILIDAD (
  ID_DISPONIBILIDAD NUMBER PRIMARY KEY,
  DIA         VARCHAR2(50 CHAR) NOT NULL,
  HORA_INICIO DATE NOT NULL,
  HORA_FIN    DATE NOT NULL,
  TIPO_SERVICIO VARCHAR2(50 CHAR) NOT NULL,
  ID_VEHICULO NUMBER NOT NULL,
  ID_USUARIO_CONDUCTOR NUMBER NOT NULL,
  CONSTRAINT CK_DISP_DIA CHECK (UPPER(DIA) IN ('LUNES','MARTES','MIERCOLES','MIÉRCOLES','JUEVES','VIERNES','SABADO','SÁBADO','DOMINGO')),
  CONSTRAINT CK_DISP_RANGO CHECK (HORA_INICIO < HORA_FIN),
  CONSTRAINT CK_DISP_TIPO CHECK (UPPER(TIPO_SERVICIO) IN ('PASAJEROS','COMIDA','MERCANCÍAS','MERCANCIAS')),
  CONSTRAINT FK_DISP_VEH FOREIGN KEY (ID_VEHICULO) REFERENCES VEHICULO(ID_VEHICULO),
  CONSTRAINT FK_DISP_COND FOREIGN KEY (ID_USUARIO_CONDUCTOR) REFERENCES USUARIO_CONDUCTOR(ID_USUARIO_CONDUCTOR)
);

CREATE TABLE RESENIA (
  ID_RESENIA NUMBER PRIMARY KEY,
  CALIFICACION INTEGER NOT NULL,
  COMENTARIO   VARCHAR2(1000 CHAR),
  FECHA DATE NOT NULL,
  ID_VIAJE NUMBER NOT NULL,
  AUTOR_ROL VARCHAR2(20) NOT NULL,
  CONSTRAINT CK_RES_CALIF CHECK (CALIFICACION BETWEEN 0 AND 5),
  CONSTRAINT CK_RES_ROL CHECK (UPPER(AUTOR_ROL) IN ('USR','COND')),
  CONSTRAINT FK_RES_VIA FOREIGN KEY (ID_VIAJE) REFERENCES VIAJE(ID_VIAJE),
  CONSTRAINT UQ_RES_UNICA UNIQUE (ID_VIAJE, AUTOR_ROL)
);

CREATE TABLE PAGO (
  ID_PAGO NUMBER PRIMARY KEY,
  MONTO   FLOAT NOT NULL,
  FECHA   DATE  NOT NULL,
  ESTADO  VARCHAR2(50 CHAR) NOT NULL,
  ID_VIAJE NUMBER NOT NULL,
  CONSTRAINT CK_PAGO_ESTADO CHECK (UPPER(ESTADO) IN ('COMPLETADO','EN ESPERA','RECHAZADO','EN ESPERA')),
  CONSTRAINT FK_PAGO_VIA FOREIGN KEY (ID_VIAJE) REFERENCES VIAJE(ID_VIAJE),
  CONSTRAINT UQ_PAGO_VIAJE UNIQUE (ID_VIAJE)
);

CREATE TABLE TARJETA_CREDITO (
  ID_TARJETA NUMBER PRIMARY KEY,
  NUMERO INTEGER NOT NULL,
  NOMBRE VARCHAR2(250 CHAR) NOT NULL,
  MES_VENCIMIENTO INTEGER NOT NULL,
  ANIO_VENCIMIENTO INTEGER NOT NULL,
  CODIGO_SEGURIDAD INTEGER NOT NULL,
  ID_USUARIO_SERVICIO NUMBER NOT NULL,
  CONSTRAINT UQ_TARJ_NUM UNIQUE (NUMERO),
  CONSTRAINT CK_TARJ_MES CHECK (MES_VENCIMIENTO BETWEEN 1 AND 12),
  CONSTRAINT CK_TARJ_ANIO CHECK (ANIO_VENCIMIENTO BETWEEN 2024 AND 2040),
  CONSTRAINT CK_TARJ_CVV CHECK (CODIGO_SEGURIDAD BETWEEN 0 AND 9999),
  CONSTRAINT FK_TARJ_USR FOREIGN KEY (ID_USUARIO_SERVICIO)
    REFERENCES USUARIO_SERVICIO(ID_USUARIO_SERVICIO)
);